package dev.noregressions.paperband.cards;

import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Element;

import java.util.ArrayList;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Strips presentation out of card content, leaving structure — the mechanism
 * behind {@link ContentPolicy}. Operates on the jsoup DOM {@code CardLoader}
 * already builds from the flexmark output, so it sees every raw-HTML island
 * in the markdown, whatever route it arrived by (typed inline, spliced by a
 * {@code {% fragment as="html" %}}, generated by an {@code {% include %}}
 * snippet, or attached via the attributes extension) — one rule, one choke
 * point.
 *
 * <p>What goes, and why:
 * <ul>
 *   <li><b>{@code <style>}, {@code <script>}, {@code <title>}</b> — dropped
 *       with their content. A stylesheet in content bypasses the theme
 *       cascade wholesale; script has no business in a book; a title is
 *       document metadata and a card is a fragment, not a document.</li>
 *   <li><b>{@code <link>}, {@code <meta>}, {@code <base>}</b> — dropped
 *       (void elements, no content to lose). Head-category metadata; the
 *       document's head is owned by the layouts/theme layer. {@code <link
 *       rel="stylesheet">} in particular is CSS smuggling past the theme.</li>
 *   <li><b>{@code <font>}, {@code <center>}</b> — unwrapped: purely
 *       presentational elements whose children are real content.</li>
 *   <li><b>Presentational attributes</b> ({@code style}, {@code align},
 *       {@code bgcolor}, {@code width}, {@code height}, …) and {@code on*}
 *       event handlers — removed from every element. {@code class} and
 *       {@code id} survive deliberately: a class is a <em>semantic</em>
 *       marker the theme styles, and the sanctioned route for everything
 *       stripped here ({@code {.name}} in markdown, a rule in the book css
 *       chain or theme).</li>
 * </ul>
 *
 * <p>Fenced code and inline code are untouched by construction: their
 * contents are escaped <em>text</em> by the time flexmark has rendered them,
 * so a literal {@code <div style="…">} in an example never appears to this
 * class as an element.
 *
 * <p><b>Inline SVG is exempt</b>, and deliberately so. Every rule above rests
 * on one distinction — appearance the theme should own, versus structure the
 * author wrote — and inside a picture that distinction collapses: a
 * {@code fill}, a {@code style}, a {@code width} on an SVG shape <em>is</em>
 * the drawing, not a decision about how the drawing should look on this
 * theme. Stripping them leaves a blank rectangle, and under
 * {@link ContentPolicy#STRICT} it would fail the build for every diagram a
 * {@link dev.noregressions.paperband.block.BlockRenderer} drew. So an
 * {@code <svg>} subtree passes through as written, with one exception that
 * isn't about presentation at all: {@code <script>} and {@code on*} handlers
 * go, wherever they are.
 */
public final class ContentSanitizer {

    /** Presentation or metadata whose content is also presentation/metadata. */
    private static final Set<String> DROP_WITH_CONTENT = Set.of("style", "script", "title");

    /** Head-category void elements: nothing inside them to preserve. */
    private static final Set<String> DROP_ELEMENT = Set.of("link", "meta", "base");

    /** Presentational wrappers whose children are real content. */
    private static final Set<String> UNWRAP = Set.of("font", "center");

    /** Attributes that carry appearance rather than meaning. */
    private static final Set<String> PRESENTATIONAL_ATTRS = Set.of(
            "style", "align", "valign", "bgcolor", "color", "background",
            "border", "hspace", "vspace", "face", "width", "height",
            "cellpadding", "cellspacing");

    /**
     * On table cells, {@code align}/{@code valign} are <em>markdown-authored
     * semantics</em>, not smuggled presentation: flexmark renders GFM's
     * {@code ---:} column syntax as {@code align} attributes on {@code th}/
     * {@code td}, so stripping them there would destroy alignment the author
     * expressed in pure markdown (found the hard way: a numeric table in a
     * real book lost its right-alignment). Everywhere else — {@code <p
     * align="center">} and friends — they stay presentation and go.
     */
    private static final Set<String> TABLE_CELL_TAGS = Set.of("th", "td");
    private static final Set<String> TABLE_CELL_KEPT = Set.of("align", "valign");

    private ContentSanitizer() {}

    /**
     * Strip presentation from {@code body}, in place.
     *
     * @param body the card body element (jsoup DOM), mutated
     * @return a human-readable description of each removal, empty when the
     *         content was already clean — the caller decides whether that
     *         list is a warning ({@link ContentPolicy#CLEAN}) or a build
     *         failure ({@link ContentPolicy#STRICT})
     */
    public static List<String> strip(Element body) {
        List<String> removed = new ArrayList<>();
        // Every element inside a picture, gathered up front: asking each
        // element "am I in an SVG?" would walk its ancestors, and a diagram is
        // thousands of elements deep in aggregate.
        Set<Element> drawing = Collections.newSetFromMap(new IdentityHashMap<>());
        for (Element svg : body.select("svg")) {
            drawing.addAll(svg.getAllElements());
        }
        // Snapshot: the walk mutates the tree it came from.
        for (Element el : new ArrayList<>(body.getAllElements())) {
            if (el == body) continue;
            String tag = el.tagName();
            if (drawing.contains(el)) {
                stripScripting(el, tag, removed);
                continue;   // the rest of a picture is the picture -- see the class javadoc
            }
            if (DROP_WITH_CONTENT.contains(tag)) {
                removed.add("dropped <" + tag + "> and its content");
                el.remove();
                continue;
            }
            if (DROP_ELEMENT.contains(tag)) {
                removed.add("dropped <" + tag + describeAttrs(el) + ">");
                el.remove();
                continue;
            }
            if (UNWRAP.contains(tag)) {
                removed.add("unwrapped <" + tag + ">");
                el.unwrap();
                continue;
            }
            for (Attribute a : new ArrayList<>(el.attributes().asList())) {
                String name = a.getKey().toLowerCase(Locale.ROOT);
                if (TABLE_CELL_TAGS.contains(tag) && TABLE_CELL_KEPT.contains(name)) {
                    continue;   // GFM column alignment — see TABLE_CELL_KEPT
                }
                if (PRESENTATIONAL_ATTRS.contains(name) || name.startsWith("on")) {
                    removed.add("stripped " + abbreviate(a.html()) + " from <" + tag + ">");
                    el.removeAttr(a.getKey());
                }
            }
        }
        return removed;
    }

    /**
     * The part of the policy that still applies inside a picture: nothing
     * executes. An {@code <svg>} island shares the page's script context like
     * any other markup, so a {@code <script>} in one is a script in the book.
     */
    private static void stripScripting(Element el, String tag, List<String> removed) {
        if (tag.equals("script")) {
            removed.add("dropped <script> inside <svg>");
            el.remove();
            return;
        }
        for (Attribute a : new ArrayList<>(el.attributes().asList())) {
            if (a.getKey().toLowerCase(Locale.ROOT).startsWith("on")) {
                removed.add("stripped " + abbreviate(a.html()) + " from <" + tag + "> inside <svg>");
                el.removeAttr(a.getKey());
            }
        }
    }

    /** The element's attributes for a removal message, abbreviated. */
    private static String describeAttrs(Element el) {
        String attrs = el.attributes().html();
        return attrs.isBlank() ? "" : abbreviate(attrs);
    }

    /** Cap a removal detail so a kilobyte of inline CSS doesn't flood the log. */
    private static String abbreviate(String s) {
        s = s.strip();
        return s.length() <= 80 ? s : s.substring(0, 77) + "...";
    }
}
